examples/chroot_vm.c, include/libkrun.h, src/libkrun/src/lib.rs
let the libkrun user specify the size of the "struct krun_config" to
help detecting mismatches between the configuration used by the user
of the library and what libkrun handles.
If the specified size is bigger than what libkrun uses, then it means
there are extra options specified by the user that libkrun cannot
honor.
We could handle the case where the specified size is less than what
libkrun knows and don't handle what is not known to the library user
but simplify usage for now and error out in both cases.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> libkrun: add config_size to KipConfig

Cargo.lock, src/arch/Cargo.toml, src/devices/Cargo.toml, src/kernel/Cargo.toml, src/vmm/Cargo.toml, src/vmm/src/builder.rs
Now that build_raw support has been merged into rust-vmm/vm-memory,
switch to it. Once released we'll be able to switch from git to
crate+version reference.
=> src: Switch to rust-vmm/vm-memory

.github/workflows/unit_tests.yml, src/arch/src/x86_64/mod.rs, src/libkrun/src/lib.rs, src/vmm/src/builder.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/kernel_bundle.rs, src/vmm/src/vmm_config/mod.rs
Move the responsibility of dealing with libkrunfw away from vmm to
libkrun, wrapping the parameters into vmm_config::KernelBundle. Also,
adapt the code to libkrunfw-0.1, which implements API versioning.
=> vmm: Refactor kernel bundle config and parameters

examples/chroot_vm.c, include/libkrun.h, src/libkrun/src/lib.rs
krun_set_exec needed the arguments to be passed as a collapsed string,
which is not what people will probably expect. Replace both the
arguments and the environment lines and use an array of string
pointers instead, just as 'execve(2)' does.
=> libkrun: Make "args" an array of string pointers

src/devices/src/virtio/vsock/unix/muxer.rs
Set TCP_NODELAY on external sockets so each packet is immediately sent.
=> vsock: set TCP_NODELAY on external sockets

src/devices/src/virtio/fs/server.rs
Actual maximum message size is MAX_BUFFER_SIZE plus the FUSE header
size. Allow messages up to that size.
=> virtiofs: Account for header in buffer size check

examples/chroot_vm.c, include/libkrun.h, src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/fs.rs
Add support for mapped volumes, so platforms that doesn't support user
namespaces (namely, macOS) can have an alternative to bind-mount for
accessing host volumes.
=> Add support for mapped volumes

init/init.c
Raise loopback interface and mount /dev/shm and cgroup2 on startup.
=> Improve init

build_on_krunvm.sh
Add a helper script for building init/init, which needs to be a Linux
ELF binary, using krunvm. This is specially useful for building
libkrun on macOS.
=> Add a helper script for building init/init on krunvm

Makefile, init/init.c
This enables the `-Wall` GCC flag and then fix the only warning emitted by the compiler.
=> Fix compiler warnings of init.c

src/libkrun/src/lib.rs
When the env vars are being collected from the current context (as
opposed of them being specified by the caller), put the values between
quotes to cope with the presence of spaces in them.
=> libkrun: Put env vars values between quotes

src/vmm/src/vmm_config/boot_source.rs
With recent Guest kernels, there appears to be an unexpected
interaction between KVM asynchronous page fault and some other VM
mechanism that causes the vCPU to return immediately to the Guest on
"hlt", leading to the thread managing vcpu 0 to spin up with ~99% of
CPU usage.
Turn KVM asynchronous page fault for the moment. We'll revisit this
issue in the future.
=> vmm: Add "no-kvmapf" to the kernel command line

src/arch/src/aarch64/fdt.rs, src/arch/src/aarch64/mod.rs, src/arch/src/lib.rs, src/arch/src/x86_64/mod.rs, src/devices/src/virtio/device.rs, src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/server.rs, src/devices/src/virtio/mmio.rs, src/vmm/src/builder.rs, src/vmm/src/lib.rs, src/vmm/src/linux/vstate.rs, src/vmm/src/vmm_config/boot_source.rs
Implement support for DAX in virtio-fs. We use a static 512MB window
at the end of the RAM. This enables the guest to bypass its own cache
for some VFS operations, reducing the amount of memory used in the
guest for its own FS cache, and increasing the number of pages we can
return to the host to free them.
This feature is supported in Linux/KVM, and has been tested on x86_64
and Aarch64. We can't use DAX on macOS, because Hypervisor.framework
doesn't allow adding MAP_SHARED maps to the VM (or, at least, I
couldn't find a way).
=> devices/fs: Implement support for DAX

src/arch/src/x86_64/regs.rs, src/vmm/src/builder.rs, src/vmm/src/linux/amdsev.rs, src/vmm/src/linux/vstate.rs
Add support for running the VM with SEV-ES. This feature is only
enabled if the attestation server requests it (that is,
PolicyFlags::ENCRYPTED_STATE is present in the Policy flags).
=> SEV: Implement support for SEV-ES

include/libkrun.h, src/devices/src/virtio/vsock/device.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/proxy.rs, src/devices/src/virtio/vsock/tcp.rs, src/devices/src/virtio/vsock/udp.rs, src/vmm/src/vmm_config/vsock.rs
On the transition from TSIv1 to TSIv2, the ability to restrict exposed
ports and configure port mappings from guest to the host was
accidentally lost. Restore it now.
=> vsock: restore lost port mapping feature

src/devices/src/virtio/vsock/mod.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/muxer_thread.rs, src/devices/src/virtio/vsock/proxy.rs, src/devices/src/virtio/vsock/reaper.rs, src/devices/src/virtio/vsock/tcp.rs, src/devices/src/virtio/vsock/udp.rs
In guests with multiple vCPUs, the request to release a sock may be
processed before all data has left the guest. This means we can't
immediately release the TSI proxy upon receiving a TsiReleaseReq
message, but we need to keep it around for a while.
Implement a reaper thread, and upon receiving a TsiReleaseReq schedule
the proxy to be freed after a timeout (5 seconds).
=> vsock: defer TSI proxy removal

src/vmm/src/vmm_config/boot_source.rs
On 5.15 kernels, a zero byte read on a DAX-enabled virtio-fs
filesystem causes the kernel to hang with a call trace like this:
[    5.363419] Call Trace:
[    5.363420]  <TASK>
[    5.363421]  dax_iomap_rw+0xa3/0xf0
[    5.363425]  fuse_dax_read_iter+0x41/0x70
[    5.363427]  fuse_file_read_iter+0x123/0x140
[    5.363430]  ? _copy_to_user+0x20/0x30
[    5.363433]  ? cp_new_stat+0x14d/0x180
[    5.363436]  new_sync_read+0x103/0x190
[    5.363438]  vfs_read+0xfa/0x190
[    5.363441]  ksys_read+0x66/0xe0
[    5.363443]  __x64_sys_read+0x14/0x20
[    5.363445]  do_syscall_64+0x37/0x80
[    5.363447]  entry_SYSCALL_64_after_hwframe+0x44/0xae
This adds up to other DAX-related issues such as the fact it breaks
PTRACE.
Let's disable virtio-fs DAX until we jump to a kernel were those
issues are …
=> Disable virtio-fs DAX

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This release includes changes in behavior:
- Disable virtio-fs DAX
- Defer TSI proxy removal
Bump minor number to v1.2.0.
=> Bump version to v1.2.0

Cargo.lock, src/arch/Cargo.toml, src/devices/Cargo.toml, src/kernel/Cargo.toml, src/vmm/Cargo.toml
Bump vm-memory dependency from 0.7.0 to 0.8.0, the latest available
version.
=> Bump vm-memory dependency from 0.7.0 to 0.8.0

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This is just a minor release updating vm-memory dependency from 0.7.0
to 0.8.0. Only bump patch number to v1.2.1.
=> Bump version to v1.2.1

Cargo.lock, Makefile, src/arch/src/x86_64/mod.rs, src/arch/src/x86_64/mptable.rs, src/cpuid/src/brand_string.rs, src/devices/src/virtio/block/device.rs, src/devices/src/virtio/block/request.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/queue.rs, src/devices/src/virtio/vsock/proxy.rs, src/kernel/src/cmdline/mod.rs, src/kernel/src/loader/mod.rs, src/libkrun/Cargo.toml, src/vmm/src/linux/vstate.rs, src/vmm/src/macos/vstate.rs, src/vmm/src/vmm_config/block.rs, src/vmm/src/vmm_config/boot_source.rs, src/vmm/src/vmm_config/fs.rs, src/vmm/src/vmm_config/machine_config.rs, src/vmm/src/vmm_config/vsock.rs
Use XATTR_NOFOLLOW with setxattr when updating the ownership and mode bits for symlinks, and return a fixed Entry on Passthrough::symlink()
=> macos: fix symlink ownership and mode attrs

init/init.c
If no HOSTNAME variable is present in the environment, set the
hostname to "localhost".
=> init: set a default hostname if no env is present

src/devices/src/virtio/fs/descriptor_utils.rs, src/devices/src/virtio/fs/file_traits.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/server.rs
Internally, the FileReadWriteAtVolatile methods are going to use
pread/pwrite family of syscalls, which implies the file descriptor
offset is not altered. With this in mind, drop the mutability
requirement on the File argument.
This change allows us to drop the "try_clone()" on
PassthroughFs::[read()|write()], saving a "dup()" syscall on both of
those critical paths.
This is a backport of virtiofsd:595126fe.
=> devices/fs: Drop mutability from FileReadWriteAtVolatile

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This release includes various fixes for macOS (concurrency issues on
Apple Silicon and tracking unlinked files) and a performance
optimization backported from virtiofsd. Just bump release to
v1.4.3.
=> Bump version to v1.4.3

src/devices/src/virtio/vsock/muxer.rs
The signal logic in Muxer was missing the ability to signal through an intc, if present. Fix it here.
=> vsock: Fix signal logic in Muxer

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This release includes a fix for the irq signal logic in vsock and updates to the final version of the KBS attestation protocol. Bump release number to v1.4.5.
=> Bump version to v1.4.5

Cargo.lock, Makefile, examples/snp-config-noattest.json, src/arch/Cargo.toml, src/arch/src/x86_64/mod.rs, src/arch/src/x86_64/regs.rs, src/devices/Cargo.toml, src/devices/src/virtio/mod.rs, src/kbs-types/Cargo.toml, src/libkrun/Cargo.toml, src/libkrun/build.rs, src/libkrun/src/lib.rs, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/lib.rs, src/vmm/src/linux/amdsev.rs, src/vmm/src/linux/mod.rs, src/vmm/src/linux/tee/amdsev.rs, src/vmm/src/linux/tee/amdsnp.rs, src/vmm/src/linux/tee/mod.rs, src/vmm/src/linux/vstate.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/boot_source.rs, src/vmm/src/vmm_config/mod.rs
This PR adds a few new features to the TEE capabilities of `libkrun`:
- Modifies the `amd-sev` module to utilize the `sev` library APIs for creating a SEV-encrypted VM.
- Introduces a new module `tee`, which serves to group all TEE-specific modules in one place.
- Introduces the ability to create AMD SEV-SNP encrypted VMs through the `amd-snp` module.
One thing missing in this PR is that although SEV-SNP VMs can be created, there is no interface for attesting a SEV-SNP VM. Attestation support is currently a WIP.
=> SEV "sev" library usage and introduced SEV-SNP support

src/vmm/src/vmm_config/boot_source.rs
Commit "00bd4c9" accidentally broke the kernel command line for non-TEE targets. Fix it here.
=> Fix kernel command line for non-TEE targets

init/init.c
While JSON is case sensitive, the reality is that we can find container configuration files where fields can be presented with arbitrary capitalization.
Use strncasecmp() instead of strncmp() to do a case-insensitive check when looking for fields in the JSON config file.
=> init: do a case-insensitive check for JSON fields

init/init.c
As the jsmn library doesn't differentiate between tokens that are keys and tokens that are values, if there's a value "env" in an arbitrary key, the parsing code in init.c will get confused and think that's the key containing the array of environment variables.
By ensuring the next token is a JSMN_ARRAY we can minimize the risk of this occurrence. If this still proves to be a problem, we might find the need to switch to a more complete JSON parsing library.
Fixes: #104
=> init: Fix parsing of Env in JSON

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This release includes a fix for JSON config parsing and makes us compatible with kvm-bindings v0.12.0, bump release number to v1.4.10
=> Bump version to v1.4.10

Cargo.lock, src/devices/Cargo.toml, src/devices/src/virtio/fs/macos/passthrough.rs
Update lru dependency to the latest available version (0.9.x), relax the dependency to acquire newer versions, and move it to the section of macos dependencies, as it's only used there.
Fixes: #98
Signed-off-by: Sergio Lopez <slp@sinrega.org>
=> devices: update lru dep to 0.9

Cargo.lock, Makefile, examples/launch-tee.c, include/libkrun.h, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/vmm/src/resources.rs
This API adds the possibility to introduce a second block device, to a TEE.
It is assumed that the root disk contains a symmetric key (secret), and code to encrypt/decrypt the data disk before use. The recommended setup is to included cryptsetup on the root disk and use that to safely access the data disk.
=> Introduce the krun_set_data_disk API.

.gitignore, Makefile, libkrun.pc.in
This allows easy detection of the package through many common build systems.  For example from autotools you might use:
```
PKG_CHECK_MODULES([LIBKRUN], [libkrun >= 1.5.0])
```
to define `$(LIBKRUN_CFLAGS)` and `$(LIBKRUN_LIBS)`.
=> Add a pkgconf file

Makefile, init/init.c, src/devices/src/virtio/vsock/mod.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/packet.rs, src/devices/src/virtio/vsock/timesync.rs
macOS can be quite aggressive when it comes to force apps to take long naps for power saving reasons. In addition to this, CNTVCT_EL0 doesn't increase during these naps, meaning the guest is not aware that's missing ticks.
Both things combined mean that guests that run for long enough will suffer from clock skews.
To address this, we introduce here a simple and lightweight host to guest time sync. From the host side, the VMM will send DGRAM packets via vsock with the current time at regular intervals (60 seconds) and when an oversleep (host thread sleeping 3 times more than expected) is detected. On the guest side, "init" spawns a process that listens for such packets and sets the system clock if a delta bigger than 100ms is detected.
Fixes: #80
=> macos: implement host->guest time sync

Makefile, init/init.c
Read the TEE config file from the end of "/dev/vda" to avoid the need of an additional block device.
This is the complement to https://github.com/virtee/oci2cw/commit/1502d5be33c2fa82d49aaa95781bbab2aa932781
=> Read TEE config from the end of the block device

init/init.c
To avoid build errors in non-SEV builds, place some remaining SEV headers and definitions behind a build-time conditional.
Replaces: #129
=> init: place SEV behind build-time conditional

Cargo.lock, Makefile, src/devices/src/virtio/vsock/device.rs, src/devices/src/virtio/vsock/event_handler.rs, src/devices/src/virtio/vsock/mod.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/muxer_thread.rs, src/devices/src/virtio/vsock/packet.rs, src/devices/src/virtio/vsock/tcp.rs, src/devices/src/virtio/vsock/udp.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/vmm/src/builder.rs, src/vmm/src/vmm_config/kernel_bundle.rs
This PR sets up the stage to support libkrunfw 4.x, which bundles a 6.4.x kernel. This is a significant update for two reasons:
- Kernel load and entry addresses no longer match, so we need to treat them independently, meaning we needed to break the API/ABI of libkrunfw.
- We've switched to a new patch series implementing datagram support for vsock, which seems very close to be accepted. This allows us to keep TSI around indefinitely, but means we needed to revamp out vsock device implementation around the semantics of this patch set.
=> Prepare to support libkrunfw 4.x

init/init.c
Previously running a non existing binary would just silently fail, now it reports an error.
Not sure about the exit code, but there are two previous exit calls, with values -1 and -2, so I just put -3 here.
=> init: Report an error when execution of the user binary fails

src/devices/src/virtio/net/device.rs, src/devices/src/virtio/net/passt.rs, src/vmm/src/vmm_config/net.rs
Since bug https://bugs.passt.top/show_bug.cgi?id=74 is now fixed in passt, it now became possible to test with small socket buffers, doing so revealed some bugs and a performance issue on the libkrun side.
If you want to test this, please use passt  0^20231004.gf851084, because of the aforementioned bug.
Note that there is now a performance issue where increasing the socket buffer sizes to the previously recommended 16Mib decreases performance. The performance of libkrun with small socket buffers is better than QEMU+passt, with bigger buffer sizes they are both kind of slow. Curiously limiting iperf3 speed (using -b) increases the performance. This seems to be another passt issue.
=> virtio net bugfixes and performance improvement

Makefile
The KBS attestation sources can be separated from the SEV-SNP attestation sources. This will make it a bit easier to introduce new TEEs in the future.
=> Makefile: De-couple KBS init sources from SEV-SNP

src/arch/src/aarch64/fdt.rs, src/devices/src/legacy/aarch64/mod.rs, src/devices/src/legacy/aarch64/serial.rs, src/devices/src/legacy/mod.rs, src/devices/src/legacy/x86_64/mod.rs, src/devices/src/legacy/x86_64/serial.rs, src/vmm/src/device_manager/hvf/mmio.rs
Import a PL011 implementation and use it when building for aarch64. While it's techicanlly possible to use a mmio 8250/16550 UART on aarch64, it's more common to have a PL011, and software such as EDK2 is built on top of this expectation.
=> devices/legacy: import PL011 for aarch64

init/init.c
Podman uses the "args" field to set the executable and the arguments to be run in the container, so parse it if found.
=> init: accept arguments from the "args" Field

include/libkrun.h, src/devices/src/virtio/vsock/device.rs, src/devices/src/virtio/vsock/mod.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/unix.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/vsock.rs
This PR introduces two main components:
1) `krun_add_vsock_port()`, which allows a user to map guest vsock port numbers to UNIX IPC sockets running on the host. With this, users can enable VM guest IPC with UNIX sockets running on a host.
2) `vsock::unix` module, implementing the `UnixProxy`, a vsock proxy that facilitates the communication between a guest vsock and UNIX IPC socket running on the host.
=> Implement `krun_add_vsock_port()` and `UnixProxy` for guest communication with host UNIX sockets.

examples/boot_efi.c, include/libkrun.h, src/arch/src/aarch64/fdt.rs, src/arch/src/lib.rs, src/devices/src/legacy/aarch64/gpio.rs, src/devices/src/legacy/aarch64/mod.rs, src/devices/src/legacy/mod.rs, src/libkrun/src/lib.rs, src/utils/src/macos/eventfd.rs, src/vmm/src/builder.rs, src/vmm/src/device_manager/hvf/mmio.rs
This PR implementes the required infrastructure to support sending a shut down signal to request the guest to orderly shutdown, and a first interface for macOS/aarch64 (should be easily portable to Linux/aarch64 too) based on the PL061 GPIO.
Consumers of the EFI variant of library can request an eventfd file descriptor with the new `krun_get_shutdown_eventfd` function, which can be used to trigger the signal by simply writing to it.
This PR also extends the `boot_efi` example to illustrate how to use it.
=> Implement the infrastructure to support sending shut down signals to the guest

include/libkrun.h, src/devices/src/virtio/net/device.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/net.rs
Extend the API to allow users to set a custom MAC for the virtio-net device.
=> devices/net: allow configuring a custom MAC

Makefile
Move base name to flavor name when building the EFI variant.
Fixes: #168
=> Makefile: fix EFI library naming

include/libkrun.h, src/devices/src/virtio/net/backend.rs, src/devices/src/virtio/net/device.rs, src/devices/src/virtio/net/event_handler.rs, src/devices/src/virtio/net/gvproxy.rs, src/devices/src/virtio/net/mod.rs, src/devices/src/virtio/net/passt.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/net.rs
Implement a backend in virtio-net compatible with the "-listen-vfkit" mode in gvproxy. In this mode, the transport operates at L2 without adding any headers, and the UNIX socket between libkrun and gvproxy operates in DGRAM mode.
=> virtio/net: implement gvproxy backend

src/utils/src/macos/eventfd.rs
We may get EAGAIN on write if the eventfd is overstimulated, but we can safely ignore it as we can be sure the subscriber will get notified.
=> macos/eventfd: ignore EAGAIN on write

src/devices/src/virtio/vsock/unix.rs
Implement the update_peer_credit method on UnixProxy, since it can be triggered by the guest anytime.
=> devices/vsock/unix: implement update_peer_credit

src/devices/src/virtio/console/port_io.rs, src/vmm/src/builder.rs
Implement PortInputEmpty and use it in OSes were PostInputSigInt is not supported.
=> devices/console: implement an empty port input

Cargo.lock, Makefile, build_on_krunvm.sh, include/libkrun.h, init/init.c, src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/mod.rs, src/devices/src/virtio/fs/server.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/rutabaga_gfx/src/virgl_renderer.rs, src/vmm/src/vmm_config/fs.rs
The hardest problem of virtio-fs is keeping a relationship between
inodes in virtio-fs (guest's perspective) and inodes in the backing
filesystem (host's perspective).
On Linux, this forces us to keep a fd open per each alive dirent in the
guest (hence the "forget/batch_forget" logic). Trying to use the same
strategy of macOS proved to be very difficult as the process can easily
reach a limit in the number of open files that can't be easily
increased.
To overcome this difficuly, we were using a complex combination of both
fd and paths caches. In this commit, we overhaul the whole
implementation to remove the use of those caches to take advange instead
of macOS ability to access inodes directly through "/.vol".
This strategy simplifies the code, reduces the cost of each operation
and makes …
=> virtio/fs/macos: overhaul to use macos inodes

src/devices/src/virtio/console/device.rs
When multiport is enabled the guest doesn't read the console size from the device config. This implies that, until SIGWINCH is received, the guest is potentially operating with a wrong console size.
To fix this issue, send a resize message on PORT_READY.
=> console: send a resize event on PORT_READY

include/libkrun.h
i.e. change `char *const *` to `const char *const *`
The problem was apparent from incorrect constness in the `bindgen` generated bindings: https://gist.github.com/teohhanhui/647227ea483dabdcd8317c6ea228665e
e.g. `*const *mut c_char` instead of the expected `*const *const c_char`, which matches https://github.com/containers/libkrun/blob/5e376689d58c1c56a22d3935722e66fe09d28685/src/libkrun/src/lib.rs
=> Fix constness when taking an array of string pointers

include/libkrun.h
See https://clang.llvm.org/docs/UsersManual.html#comment-parsing-options
This helps to have the doc comments carry over to the `bindgen`-generated Rust bindings. See https://docs.rs/bindgen/0.69.4/bindgen/struct.Builder.html#method.generate_comments
=> Use the correct documentation comment style recognized by clang

Cargo.lock, Makefile, include/libkrun.h, src/devices/Cargo.toml, src/devices/src/virtio/mod.rs, src/devices/src/virtio/queue.rs, src/devices/src/virtio/snd/audio_backends.rs, src/devices/src/virtio/snd/audio_backends/pipewire.rs, src/devices/src/virtio/snd/audio_backends/pipewire/test_utils.rs, src/devices/src/virtio/snd/device.rs, src/devices/src/virtio/snd/mod.rs, src/devices/src/virtio/snd/stream.rs, src/devices/src/virtio/snd/virtio_sound.rs, src/devices/src/virtio/snd/worker.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/resources.rs
Import a virtio-snd device from vhost-user-sound, trying to preserve as
much as possible of the original semantics to we can eventually consume
that crate if transitions to expose the device personality
indenendently.
=> virtio/snd: import virtio-snd from vhost-user-sound

src/vmm/src/builder.rs
If the "net" feature is enabled, only pass "tsi_hijack" to the kernel if there are no network devices configured.
=> builder: only enable TSI if there are no netdevs

init/init.c
Tell the kernel that we want to ignore SIGCHLD so it'll reap our children for us to avoid leaving zombie objects.
Fixes #189
=> init: tell the kernel to reap our children for us

src/devices/src/virtio/fs/linux/passthrough.rs
The dirent name length is supposed to be the actual `strlen()` of the name, without any padding. `SYS_getdents64`, however, will pad the records it returns (for alignment, etc.) as well as NUL-terminate the name.
This was causing dirents in the guest kernel to have spurious NUL padding treated as part of the name, which in turn was breaking `getcwd()` under some conditions (and probably other more subtle things).
=> virtio/fs: Fix corrupted dirents due to trailing garbage

Cargo.lock, Makefile, src/arch/Cargo.toml, src/cpuid/Cargo.toml, src/libkrun/Cargo.toml, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/lib.rs, src/vmm/src/linux/vstate.rs, src/vmm/src/macos/vstate.rs
Update kvm-bindings to 0.8 and kvm-ioctls to 0.17, and apply some minor changes to vmm to overcome the API-breaking changes in the latter.
=>  Update kvm-bindings and kvm-ioctls deps

Makefile, src/devices/Cargo.toml, src/devices/src/virtio/gpu/virtio_gpu.rs, src/libkrun/Cargo.toml, src/rutabaga_gfx/Cargo.toml, src/rutabaga_gfx/src/generated/virgl_renderer_bindings.rs, src/rutabaga_gfx/src/rutabaga_core.rs, src/rutabaga_gfx/src/virgl_renderer.rs
Use rutabaga's resource_map() to delegate mappings to virglrenderer.
This allows libkrun + virglrenderer to map BOs without relying on PRIME
fds, simplifying the ability to honor BO sharing semantics
The feature is gated behind "virgl_resource_map2" until
https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1374
gets merged.
=> gpu: use resource_map() for mapping BOs

src/hvf/src/lib.rs
This is part of the ARM Power State Coordination Interface, see https://developer.arm.com/documentation/den0022/f/?lang=en
There are 2 calls: 1 for "system off" and one for "system reset". Previously we supported only "system reset", add support for "system off" as well.
I tested with a small Go `init` process which ran:
```
func main() {
_ = syscall.Reboot(syscall.LINUX_REBOOT_CMD_POWER_OFF)
}
```
Before the patch it would keep running. After this patch it powers off as expected.
=> hvf: support ARM PSCI SYSTEM_OFF

src/devices/src/virtio/console/device.rs
Using the raw ioctl can cause UB that manifest on some versions of the compiler. Use nix's ioctl_read_bad to generate a proper ioctl wrapper.
=> console: avoid using the raw ioctl for TIOCGWINSZ

src/vmm/src/vmm_config/boot_source.rs
I noticed this kernel parameter was incorrect in the command-line (torvalds/linux@02608bef8f774c058779546926889a2f2717a499).  It looks like it will have no effect since the default libkrunfw configs disable `CONFIG_MODULES`, so the code that handles this parameter isn't built.  Maybe the parameter could be dropped, but this corrects it to take effect if anyone tries to use a modular kernel.
=> vmm: Fix the nomodule kernel parameter

src/devices/src/virtio/fs/macos/passthrough.rs
Before this patch on virtiofs we had:
```
$ fallocate -o 0 -l 1024 f
$ ls -l f
-rw-r--r--    1 root     root          1024 Jun 24 13:00 f
$ fallocate -o 0 -l 512 f
$ ls -l f
-rw-r--r--    1 root     root           512 Jun 24 13:00 f
```
Unfortunately the second `fallocate` call caused the file to shrink, due to the call to `ftruncate`.
On a tmpfs for comparison the file doesn't shrink:
```
$ fallocate -o 0 -l 1024 f
$ ls -l f
-rw-r--r--    1 root     root          1024 Jun 24 12:55 f
$ fallocate -o 0 -l 512 f
$ ls -l f
-rw-r--r--    1 root     root          1024 Jun 24 12:56 f
```
This patch only calls ftuncate() if the proposed_length is larger than the current length.
=> virtiofs: fallocate: should enlarge but not shrink the file

src/devices/src/legacy/gic.rs, src/devices/src/legacy/mod.rs, src/vmm/src/builder.rs, src/vmm/src/macos/vstate.rs
Instead of locking a single Gic, we move the contention down to the vCPU level.
This gives us better performance for CPU bound tasks.
On a 8 cores M3:
+ Building the Linux Kernel: 7m21s -> 6:58s
+ Building Wasmer: 3m13s -> 2m30s
=> Remove contention on the Gic

Cargo.lock, Makefile, src/libkrun/Cargo.toml, src/vmm/Cargo.toml, src/vmm/src/linux/tee/amdsev.rs, src/vmm/src/linux/tee/amdsnp.rs
This allows us to also update sev to the latest version, 3.2.0.
=> Update kbs-types dependency to 0.7.0

src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/fuse.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/server.rs
Fix submount navigation by decoupling host<->guest inode numbers and implementing support for FUSE SUBMOUNTS, based on virtiofsd implementation.
=> virtio/fs/macos: fix submounts

include/libkrun.h, src/arch/src/aarch64/mod.rs, src/arch/src/lib.rs, src/arch/src/x86_64/mod.rs, src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/server.rs, src/devices/src/virtio/fs/worker.rs, src/devices/src/virtio/gpu/worker.rs, src/devices/src/virtio/mmio.rs, src/devices/src/virtio/queue.rs, src/devices/src/virtio/vsock/muxer_rxq.rs, src/devices/src/virtio/vsock/packet.rs, src/libkrun/src/lib.rs, src/utils/src/linux/epoll.rs, src/vmm/src/builder.rs, src/vmm/src/device_manager/mod.rs, src/vmm/src/device_manager/shm.rs, src/vmm/src/lib.rs, src/vmm/src/linux/vstate.rs, src/vmm/src/macos/vstate.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/fs.rs
We have multiple devices (fs and gpu) that can use SHM regions. So far,
we were creating a single SHM region so only one device could make use
of it. In this commit, we implement SHM region management so multiple
devices can request their own regions.
For the moment, we're hardcoding the SHM region sizes for gpu and fs. A
future commit will extend the API so users can configure those sizes as
desired.
=> Implement SHM region management and re-enable DAX in virtiofs

src/vmm/src/device_manager/kvm/mmio.rs
Follow up of 5329be7 commit. It is more common to have a PL011 than UART.
=> devices/legacy: use pl011 for earlycon in aarch64

README.md, include/libkrun.h, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/block.rs
This generalizes over krun_set_{root,data}_disk(). Notably:
* It allows arbitrarily many disk images.
* It allows mounting disks read-only.
To implement, we refactor a bit the existing handling while allowing
both APIs to be used together.
This is required to mount systemwide squashfs images which Asahi will use for FEX.
=> Add krun_add_disk() method

init/init.c
So far, the configuration was always expected to be in "/.krun_config.json". To support it to be located elsewhere, use the path stored in KRUN_CONFIG, falling back to the original location if not found there.
=> init: support other locations for krun_config

src/devices/src/virtio/block/worker.rs, src/devices/src/virtio/console/port.rs, src/devices/src/virtio/fs/worker.rs, src/devices/src/virtio/gpu/worker.rs, src/devices/src/virtio/net/worker.rs, src/devices/src/virtio/snd/worker.rs, src/devices/src/virtio/vsock/muxer_thread.rs, src/devices/src/virtio/vsock/reaper.rs, src/devices/src/virtio/vsock/timesync.rs, src/libkrun/src/lib.rs
Helps debugging with gdb, otherwise they inherit another thread name and it gets confusing.
=> virtio, krun: Name all the worker threads

src/devices/src/virtio/fs/linux/passthrough.rs
The f\*attr library of functions only works on files opened normally. Symlinks can only be opened with O_PATH, but that doesn't support xattr operations. So, to handle symlinks, we need to use the l\*attr family of functions directly on the pathname.
Thankfully, this does still work via /proc/self/fd/\* for fds opened with O_PATH, so we can still do fd-relative operations (l\*attr on such a path resolves the magic symlink and operates on the symlink that is actually opened as that fd).
This fixes `ls: bin: Too many levels of symbolic links` errors in the guest when SELinux attributes are in use.
=> virtio/fs/linux: Fix xattrs on symlinks

src/devices/src/virtio/fs/linux/passthrough.rs
Used the wrong function on CString...
=> virtio/fs/linux: Fix xattrs on symlinks (leak fix)

src/devices/src/virtio/fs/linux/passthrough.rs
The fd is owned, so it will be closed on drop. Fixes race condition that could sometimes cause another file to be closed.
=> virtio/fs/linux: Fix redundant close()

src/vmm/src/device_manager/shm.rs
GuestMemoryMmap requires guest ranges to be sorted by start address, so use a BTreeMap instead of a HashMap to keep the order consistent.
=> device_manager: Keep SHM region order

src/rutabaga_gfx/src/cross_domain/sys/unix.rs
This was spuriously returning hung_up: true when no hangup occurred.
=> rutabaga: cross_domain: Fix EPOLLRDHUP logic

src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/mod.rs, src/devices/src/virtio/gpu/device.rs, src/devices/src/virtio/gpu/virtio_gpu.rs, src/devices/src/virtio/gpu/worker.rs, src/rutabaga_gfx/src/cross_domain/mod.rs, src/rutabaga_gfx/src/rutabaga_core.rs, src/vmm/src/builder.rs
Prep work for the X11 channel type that does not strictly implement the code. This will be a dependency of #213.
Most of this is implementing support for sharing file handles between the FS code and the GPU code, to implement fence passing. Please let me know if this approach looks sensible.
=> X11 cross-domain prep work

src/devices/Cargo.toml, src/devices/src/virtio/gpu/virtio_gpu.rs, src/rutabaga_gfx/ffi/src/include/rutabaga_gfx_ffi.h, src/rutabaga_gfx/ffi/src/tests/virtgpu_cross_domain_protocol.h, src/rutabaga_gfx/src/cross_domain/cross_domain_protocol.rs, src/rutabaga_gfx/src/cross_domain/mod.rs, src/rutabaga_gfx/src/cross_domain/sys/unix.rs, src/rutabaga_gfx/src/rutabaga_utils.rs
Add the X11 cross domain channel type and futex sharing. This is the new approach using explicit FD passing, which depends on #231 (will rebase once that is merged). Also includes a bunch of bug fixes over the previous PR, and CI now passes. I think this should be good to start reviewing.
This approach no longer needs the `LD_PRELOAD`. You can just use nothing (the ptrace code in x112virtgpu should be more robust now), or `xshmwrap` (packaged with x112virgpu) to avoid the ptrace hack. I also sent a [PR](https://gitlab.freedesktop.org/xorg/lib/libxshmfence/-/merge_requests/9) upstream to libxshmfence so we can do this with a simple env var in the future, without hacks.
Compared to #213, this removes the rootfs DAX enablement, but I think @slp wants to do the DAX toggle another way anyway. …
=> X11 passthrough and futex sharing

Cargo.lock, include/libkrun.h, src/devices/Cargo.toml, src/devices/src/virtio/block/device.rs, src/devices/src/virtio/block/mod.rs, src/devices/src/virtio/block/worker.rs, src/devices/src/virtio/file_traits.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/block.rs
Use the [imago](https://www.gitlab.com/hreitz/imago) crate to add support for multiple disk image types. This specifically adds support for the use of both Raw and Qcow2 disk images.
=> Add support for Qcow2 disk images

src/arch/src/x86_64/layout.rs, src/devices/src/virtio/descriptor_utils.rs, src/devices/src/virtio/file_traits.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/server.rs, src/devices/src/virtio/net/worker.rs, src/devices/src/virtio/queue.rs, src/hvf/src/lib.rs, src/vmm/src/vmm_config/boot_source.rs
Fix a "needless lifetimes" linting failure.
First seen in https://www.github.com/containers/libkrun/pull/237
=> Fix Code Quality failure

src/hvf/src/lib.rs, src/vmm/src/macos/vstate.rs
For correctness and to support IPIs in future GICv3 implementations, we need to ensure each HVF vCPU runs in the right thread, so their respective IDs match each other.
We can't supply an ID to hv_vcpu_create. Instead, it'll return an incremental integer each time we call it. In order to have deterministic IDs, we need to serialize each call.
As we already have a Sender for notifying each vCPU TLS initialization, let's reuse and simply deplay writting to it until hv_vcpu_create has been called.
While there, also set MPIDR to the same vCPU ID, as this will be needed to properly support the in-kernel HVF GICv3 implementation.
=> hvf: ensure vcpus run in the right thread

include/libkrun.h, src/devices/src/virtio/vsock/device.rs, src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/muxer_thread.rs, src/devices/src/virtio/vsock/proxy.rs, src/devices/src/virtio/vsock/tcp.rs, src/devices/src/virtio/vsock/unix.rs, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/vsock.rs
Previously all vsocks were expected to be connected from the guest. This patch adds support for sockets that are listened to by the guest and are connected from the host.
=> net: Allow creating vsocks in listen mode.

src/devices/src/virtio/gpu/virtio_gpu.rs, src/rutabaga_gfx/ffi/src/include/rutabaga_gfx_ffi.h, src/rutabaga_gfx/ffi/src/tests/virtgpu_cross_domain_protocol.h, src/rutabaga_gfx/src/cross_domain/cross_domain_protocol.rs, src/rutabaga_gfx/src/cross_domain/mod.rs, src/rutabaga_gfx/src/cross_domain/sys/mod.rs, src/rutabaga_gfx/src/cross_domain/sys/stub.rs, src/rutabaga_gfx/src/cross_domain/sys/unix.rs, src/rutabaga_gfx/src/rutabaga_utils.rs
This extends the already existing wayland/x11 cross domain channel to also work for sharing pipewire between host and guest. The necessary changes are eventfd support (inspired by how wayland pipes are handled), a few fixes to sharing shm buffers, and a new protocol version that supports more fds per message (pw can sometimes send more than 4).
=> Add pipewire cross domain channel type.

src/devices/src/virtio/net/gvproxy.rs, src/devices/src/virtio/vsock/unix.rs
It's invalid, useless, and will generate an error from 6.12.9 onwards:
https://lore.kernel.org/all/20241231160527.3994168-1-edumazet@google.com/
Fixes: #250
Suggested-by: Janne Grunau <j@jannau.net>
=> Don't use SO_REUSEPORT with UNIX sockets

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This version includes a new GICv3 for macOS and a new API for using qcow2 disks based on the imago crate. I think these changes justify bumping the minor number too.
=> Bump version to 1.10.0

src/devices/src/virtio/console/port_io.rs
This fixes a hang observed when the VM is about to exit. The problem was the console device was joining a thread on vm shutdown (or device reset) which would never exit.
To replicate the hang, the stdin must not be a terminal (for example you can use a pipe).
Before this fix, this would hang:
`echo hello | ./chroot_vm rootfs_fedora /bin/cat`
(Btw libkrun used 100% (1 core) of CPU when it was stuck in this state - I don't know why exactly.)
This seems to be a regression introduced by the commit: `4076b7`: devices/console: implement reset method
=> devices/console: Fix a bug which would cause libkrun to hang on exit

src/devices/src/virtio/mmio.rs
Addresses: https://github.com/containers/krunkit/issues/32
=> demote WARN log to DEBUG

src/devices/src/virtio/net/gvproxy.rs
Connecting to the socket set the remote address so we can use 
send()/recv() or write()/read() instead of sendto()/recvfrom().
Advantages:
- Simpler code, no need to keep the remote address.
- The server will want to connect to the client address to ensure it
receives frames only from the connected client. Such server will want
to remove the unix socket once the client connected[2], which doe snot
work with current code.
- Once the socket is connected, the same backend can be used to handle
passed file descriptor[1].
- iperf3 -R is 1.33 times faster (46.6 Gbits/s vs 35.0 Gbits/s).
Tested with:
For testing results see 
https://github.com/containers/libkrun/issues/264#issuecomment-2640338792
[1] https://github.com/containers/krunkit/issues/24
[2] …
=> Connect to gvproxy socket

Makefile
Add .PHONY to to the release and debug library targets so running make does the right thing after changing the source.
It is possible to use cargo directly, but this means a developer need to also run the more commands manually for each build which is error prone.
=> Fix incremental builds using make

libkrun.pc.in
Add variables for the headers and libraries to Cflags and Libs. This fixes non-system-wide installations of libkrun referenced by using PKG_CONFIG_PATH.
=> libkrun.pc.in: add libs and cflags directories

Cargo.lock, examples/Makefile, examples/external_kernel.c, include/libkrun.h, src/arch/src/aarch64/mod.rs, src/arch/src/lib.rs, src/arch/src/x86_64/mod.rs, src/libkrun/Cargo.toml, src/libkrun/build.rs, src/libkrun/src/lib.rs, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/external_kernel.rs, src/vmm/src/vmm_config/mod.rs
This PR makes libkrunfw optional (by dynamically loading it) and adds
support for loading external kernels from multiple image formats. The
ones currently implemented are:
- ELF: A kernel binary in ELF format (vmlinux).
- PeGz: A PE binary embedding a kernel image compressed with GZIP.
- ImageBz2: An Image file embedding a kernel compressed with BZIP2.
- ImageGz: An Image file embedding a kernel compressed with GZIP.
- ImageZstd: An Image file embedding a kernel compressed with ZSTD.
Adding new kernel formats should be quite straightforward.
Please note this change doesn't implement support for loading an
external initramfs. The main reason is that we can't guarantee to
maintain the control of the VM boot when using an arbitrary
initramfs.
This means that the external kernel must be built …
=> Support loading external kernels

src/libkrun/src/lib.rs
In the last iteration of PR#256 we introduced the use of LazyLock, which helps us load the library earlier. The implementation was wronging because we were unwrapping if the library is missing, which is exactly what we were trying to prevent.
Replace the value with an Option, which allows us to avoid the unwrap and actually achieves the purpose of making libkrunfw optional.
=> libkrun: avoid failing when libkrunfw is missing

src/devices/src/virtio/vsock/proxy.rs, src/devices/src/virtio/vsock/tcp.rs, tests/run.sh, tests/test_cases/src/lib.rs, tests/test_cases/src/tcp_tester.rs, tests/test_cases/src/test_tsi_tcp_guest_connect.rs, tests/test_cases/src/test_tsi_tcp_guest_listen.rs
This PR adds a simple tests that attempts to connect to a TCP socket on host from the guest. However this would often fail, due to a race condition:
As far as I understand, this is what happens:
`libkrun` connects to the TCP socket on the host (this action is done upon the TSI_CONNECT request), but the guest is not connected to stream vsock socket corresponding to the actual transport for that connection. (We have not called `confirm_connect`).  The problem is that since we assume the guest is already connected we attempt to recv here:
https://github.com/containers/libkrun/blob/a84dc1ac44c20713deff11343647ee51f5fc7931/src/devices/src/virtio/vsock/tcp.rs#L700-L714
This returns `wait_credit = true`, which causes us to send `VSOCK_OP_CREDIT_REQUEST` before sending the `VSOCK_OP_RESPONSE` to …
=> vsock: TCP test + fix a bug leading to an error in TCP connect call in guest 

.cirrus.yml
Add integrations tests to the Cirrus running based on Matej's recent work.
=> ci: add integration tests

src/libkrun/src/lib.rs
In e789b3f4da2479bf64645eac76d6ee6179def456 I broke the logic, which only created the shutdown_efd on the efi flavor, to only create it on the tee flavor, which doesn't make sense. Fix it here.
=> libkrun: fix shutdown_efd for efi flavor

include/libkrun.h, src/libkrun/src/lib.rs
If I want to attach a host block device to a microVM, the `/dev/disk*` or `/dev/rdisk*` file needs to be opened by root.
However, I would like to avoid having to run the VMM as root too. Once the device is opened, we can drop privileges using setuid/setgid. This needs to happen inside `krun_start_enter` after setting up the device but before the virtual machine is started.
This can be solved by introducing two new configuration functions `krun_setuid` and `krun_setgid`.
=> Added new functions: krun_setuid, krun_setgid

src/devices/src/virtio/vsock/muxer.rs, src/devices/src/virtio/vsock/proxy.rs, src/devices/src/virtio/vsock/tcp.rs, src/devices/src/virtio/vsock/unix.rs, tests/test_cases/src/tcp_tester.rs
This fixes #294 while implementing another approach for fixing the problem addressed by 3bd3b98916eed4816ec19bc627c94edf87695090
=> Revert "vsock: Fix TCP connection bug" and implement a different approach

src/devices/src/virtio/block/device.rs, src/libkrun/src/lib.rs
=> devices: set CacheType::Unsafe for macOS raw disks

Makefile, src/libkrun/build.rs
Using patchelf to set soname in the library has always been kind of a hack. Let's get rid of it.
=> libkrun: stop using patchelf

src/vmm/src/linux/vstate.rs
On aarch64, we receive the shutdown/reset signals as KVM SystemEvents. Let's identify them properly to avoid printing an error on exit.
=> vmm/linux/vstate: support KVM SystemEvents

init/init.c
Support "Cwd" in addition to "WorkingDir" as workdir, as both seem to be used indistinctively.
=> init: support cwd as workdir

.clang-format, .github/workflows/code_quality-aarch64-darwin.yml, .github/workflows/code_quality-aarch64.yml, .github/workflows/code_quality-x86_64.yml, init/init.c, init/jsmn.h, init/tee/kbs/kbs.h, init/tee/kbs/kbs_crypto.c, init/tee/kbs/kbs_curl.c, init/tee/kbs/kbs_types.c, init/tee/kbs/kbs_util.c, init/tee/snp_attest.c, init/tee/snp_attest.h
While we use rustfmt and clippy for Rust code, we never settled on a
coding style for the C portions of the project (the init binary). This
has caused the files to divert in style, and in some cases to have
multiple styles mixed in.
Let's settle on a coding style, based on LLVM with a few tweaks to make
it reasonably close to what we were doing so far. We do this by adding
a clang-format configuration file and formatting existing files.
The next commit will extend the tests to ensure PRs adhere to the coding
style in clang-format.
=> init: set up code style and format files

init/init.c
Allow `Entrypoint` to be passed after the other tokens.
Drive-by PR.
I hope the PR makes sense.
=> init: use parsed_entrypoint in if condition

src/hvf/src/lib.rs
The second argument is a bool, not a pointer to a bool.
=> hvf: fix set_el2_enabled function signature

Cargo.lock, examples/chroot_vm.c, include/libkrun.h, src/devices/src/legacy/ioapic.rs, src/devices/src/legacy/mod.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/utils/src/lib.rs, src/utils/src/sized_vec.rs, src/vmm/src/builder.rs, src/vmm/src/device_manager/kvm/mmio.rs, src/vmm/src/resources.rs
Allow the user to specify if they want to split the IRQCHIP such that the LAPIC is still inside the guest, but the IOAPIC is in userspace and managed by the VMM.
Intel Trust Domain Extensions, for example, require this functionality to work.
The Intel specification for the device can be found here: https://pdos.csail.mit.edu/6.828/2016/readings/ia32/ioapic.pdf
=> Add support for userspace IOAPIC

include/libkrun.h, src/hvf/src/lib.rs, src/libkrun/src/lib.rs
Add an API to check if the current system supports Nested Virt on macOS.
=> hvf: Add API to verify Nested Virt is supported

src/arch_gen/Cargo.toml
Adding the Cargo edition for the `arch_gen` crate will get rid of the warning every time the project is built saying the Cargo edition is defaulting to 2015.
=> arch_gen: add Cargo edition

Cargo.lock, src/devices/src/legacy/ioapic.rs, src/devices/src/legacy/mod.rs, src/devices/src/virtio/fs/device.rs, src/devices/src/virtio/fs/filesystem.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/devices/src/virtio/fs/server.rs, src/devices/src/virtio/fs/worker.rs, src/devices/src/virtio/gpu/device.rs, src/devices/src/virtio/gpu/virtio_gpu.rs, src/devices/src/virtio/gpu/worker.rs, src/hvf/src/lib.rs, src/libkrun/src/lib.rs, src/utils/Cargo.toml, src/utils/src/lib.rs, src/utils/src/worker_message.rs, src/vmm/src/builder.rs, src/vmm/src/lib.rs, src/vmm/src/linux/vstate.rs, src/vmm/src/worker.rs
Whenever the vCPU needs to access resources the Vm or Vmm has control over, we end up spawning a worker thread to complete the task. Rather than spawning a new worker thread for each task, use a single thread, but make the message that's passed generic to allow for multiple use cases.
=> Consolidate worker threads

Cargo.lock, Makefile, src/libkrun/Cargo.toml
This is a minor security release to address a vulnerability in crossbeam-channel (CVE-2025-4574).
=> Bump version to 1.12.1

Cargo.lock, src/vmm/Cargo.toml, src/vmm/src/linux/vstate.rs
It's not packaged in Fedora and I don't think it adds enough value to justify its addition.
=> vmm: drop use of rangemap crate

Cargo.lock, examples/chroot_vm.c, include/libkrun.h, src/devices/Cargo.toml, src/hvf/Cargo.toml, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/utils/Cargo.toml, src/vmm/Cargo.toml, tests/runner/Cargo.toml
Introduce a new krun_init_log public API function to allow for much detailed configuration of logging by the application. The main improvment is the ability to specify a file descriptor to write the log to.
This can be tested using the added `chroot_vm` flags: `--log=/path/to/a/pipe` or  `--color-log=/path/to/a/pipe` (which will also display a formatting).
=> Introduce a new krun_init_log() API

src/hvf/src/lib.rs
This fixes nested virt on M4 devices.
=> hvf: mask SME in ID_AA64PFR1_EL1

Cargo.lock, Makefile, src/libkrun/Cargo.toml
Set up the stage for a new release, including fixes for nested virt in M4, aarch64 registers, and a new log API.
=> Bump version to 1.13.0

Makefile
This tweaks the `EFI=1` make option so that it doesn't automatically bring along the `gpu` feature. Since `EFI` resets `FEATURE_FLAGS`, the test for `GPU` and `SND` (not implied by `efi` rust feature) are evaluated after.
=> Tweak the Makefile to decouple EFI and GPU features

.github/workflows/code_quality-aarch64-darwin.yml, Cargo.lock, Makefile, examples/Makefile, examples/nitro.c, include/libkrun.h, src/devices/Cargo.toml, src/devices/src/virtio/mod.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/nitro/Cargo.toml, src/nitro/src/error.rs, src/nitro/src/lib.rs, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/device_manager/shm.rs
This PR adds a new flavor, `libkrun-nitro`. The nitro flavor is expected to be run on AWS EC2 instances that support [AWS Nitro Enclaves](https://aws.amazon.com/ec2/nitro/nitro-enclaves/).
AWS Nitro Enclaves are fully isolated and highly constrained virtual machines that run on the Nitro hypervisor. CPUs and memory of an enclave are completely isolated from a parent instance and other users of a system, significantly reducing the attack surface and helping to prevent the stealing/tampering of data.
To demo on an AWS EC2 instance with Nitro Enclaves enabled:
- Clone repo, checkout the `nitro` branch
```
$ git clone https://github.com/tylerfanelli/libkrun.git
$ cd libkrun
$ git checkout nitro
```
- Build the `libkrun-nitro` flavor
```
$ make NITRO=1
$ make install NITRO=1
$ ln …
```
=> Preliminary support for AWS Nitro Enclaves

src/vmm/src/worker.rs
If the worker thread panics when trying to convert memory to or from
private, it leaves the VMM process waiting indefinitely for the sender
to send some sort of message over the channel. Rather than panicking, we
should print an error and send a message back over the channel to stop
the VM.
=> vmm: fix worker thread panic

examples/boot_efi.c, examples/chroot_vm.c, examples/external_kernel.c, include/libkrun.h, src/devices/src/virtio/net/device.rs, src/devices/src/virtio/net/mod.rs, src/devices/src/virtio/net/unixgram.rs, src/devices/src/virtio/net/unixstream.rs, src/devices/src/virtio/net/worker.rs, src/libkrun/src/lib.rs, src/vmm/src/builder.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/net.rs
So far, we were assuming the microVM will have a single network interface. But we have at least one new usecase (namely, running Android), that requires having multiple interfaces.
Refactor the API to support adding mulitple interfaces, while we keep compatibility with the old API.
While there, also allow the user to set up the network device flags.
=> net: support multiple network interfaces

Cargo.lock, examples/nitro.c, include/libkrun.h, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/nitro/Cargo.toml, src/nitro/src/enclaves.rs
Allow callers of the libkrun-nitro API to be responsible for connecting the vsock infrastructure needed for console output, rather than the nitro crate. Also add some documentation clarifications w/r/t the libkrun API in the nitro flavor.
=> nitro: Remove vsock proxying + documentation additions

.github/workflows/code_quality-x86_64.yml, Cargo.lock, Makefile, README.md, examples/Makefile, examples/launch-tee.c, examples/tdx-config-noattest.json, init/init.c, src/arch/Cargo.toml, src/arch/src/x86_64/mod.rs, src/cpuid/Cargo.toml, src/cpuid/src/transformer/intel.rs, src/devices/Cargo.toml, src/devices/src/legacy/ioapic.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/utils/Cargo.toml, src/vmm/Cargo.toml, src/vmm/src/builder.rs, src/vmm/src/linux/tee/inteltdx.rs, src/vmm/src/linux/tee/mod.rs, src/vmm/src/linux/vstate.rs
This pull request adds support for Intel Trust Domain eXtensions (TDX), another hardware Trusted Execution Environment architecture.
Note: this pull request does not support attestation.
=> Add preliminary Intel TDX support [v2]

src/vmm/src/linux/vstate.rs
Pointer authentication is an Arm CPU feature that may be used to mitigate
against various security vulnerabilities. It is not exposed to KVM guests
by default, so do so.
Signed-off-by: Peter Collingbourne <pcc@google.com>
=> aarch64: Expose pointer authentication to guests

Cargo.lock, include/libkrun.h, init/init.c, src/devices/src/virtio/fs/linux/passthrough.rs, src/devices/src/virtio/fs/macos/passthrough.rs, src/libkrun/Cargo.toml, src/libkrun/src/lib.rs, src/vmm/src/vmm_config/block.rs
I had an idea how to simplify booting from block devices. Since `init.krun` is a virtual file implemented in the virtiofs `passthrough` module, we'd normally have to manually copy it to the device from which we want to boot and also adjust kernel cmdline to override the default root settings.
Instead, if `krun_set_root()` was never called but there is a block device, we can still create a dummy rootfs just for executing init and then switch to the real root with a similar mechanism initramfs would use.
This relies on setting `KRUN_BLOCK_ROOT` environment variable (internally) as well as reading `/proc/filesystems` so we can implement the behavior of `mount -t auto` for the real root.
I also added another custom ioctl which I use for cleaning up the temporary root when no longer needed.
=> Simplify booting from block devices

include/libkrun.h, src/devices/src/virtio/net/backend.rs, src/devices/src/virtio/net/device.rs, src/devices/src/virtio/net/mod.rs, src/devices/src/virtio/net/tap.rs, src/devices/src/virtio/net/unixgram.rs, src/devices/src/virtio/net/unixstream.rs, src/devices/src/virtio/net/worker.rs, src/libkrun/src/lib.rs
Implement a new backend that allows network interfaces to use a tap device on the host to read/write frames.
=> net: implement a backend for tap devices

src/libkrun/src/lib.rs, src/vmm/src/builder.rs, src/vmm/src/resources.rs, src/vmm/src/vmm_config/boot_source.rs
All settings like exec path, working directory, rlimits or any custom environment variables are ignored if there is an external kernel configured with a non-empty cmdline. This PR addresses the issue.
=> KRUN_* environment variables should be preserved when a custom kernel cmdline is configured

src/devices/src/virtio/console/device.rs
If the device backing the port is not a TTY, it is expected that we'll receive an ENOTTY error. Avoid logging an error in that case.
=> console: avoid logging error on ENOTTY

Cargo.lock, Makefile, src/libkrun/Cargo.toml
Set up the stage for a quick bug-fix release including a patch fixing network configuration with unixgram sockets (#402).
=> Bump version to 1.15.1

src/rutabaga_gfx/src/cross_domain/cross_domain_protocol.rs, src/rutabaga_gfx/src/cross_domain/mod.rs
I've been trying to get the Wayland forwarding to work as well as on crosvm.. With these fixes both sommelier and wayland-proxy-virtwl do actually work in muvm.
See the commit messages for details.
(is there any custom krun-specific client relying on `CROSS_DOMAIN_MAX_IDENTIFIERS: usize = 4;` ? :thinking:)
=> rutabaga_gfx: fixes for wayland/sommelier

src/devices/src/legacy/kvmgicv2.rs, src/devices/src/legacy/kvmgicv3.rs, src/devices/src/legacy/mod.rs, src/vmm/src/builder.rs
The SoC in some popular boards (namely, the RPi family) doesn't support an architected vGIC, which is required for requesting KVM the instantiation of a GICv3. To relieve the users from having to configure the gic version manually, try first to instantiate a GICv3, and fall back to a GICv2 if it fails.
Fixes: #420
=> Fall back to GICv2 if GICv3 is not supported
