- Cargo.lock
- examples/chroot_vm.c
- include/libkrun.h
- src/libkrun/Cargo.toml
- src/libkrun/src/lib.rs
Refactor the public C API to add versioning and make it more granular,
so we can extend it without breaking existing users.
> libkrun: Refactor the API to make it future-proof

- src/vmm/src/vstate.rs
Have the builder thread wait for the initialization of the TLS for each
vCPU worker thread. Otherwise, the VcpuEvent::Resume event, which needs
to be processed on the vCPU local thread, may arrive before the TLS has
been initialized, causing a SIGSEGV.
This issue can be easily reproduced when configuring VMs with 8 or more
vCPUs.
> vmm: Serialize vcpu TLS initialization

- examples/chroot_vm.c
- include/libkrun.h
- src/devices/src/legacy/rtc_pl031.rs
- src/devices/src/virtio/vsock/csm/connection.rs
- src/devices/src/virtio/vsock/csm/mod.rs
- src/devices/src/virtio/vsock/mod.rs
- src/devices/src/virtio/vsock/unix/mod.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/libkrun/src/lib.rs
- src/vmm/src/vmm_config/vsock.rs
Implement support for RESPONSE_EX, host to guest port maps, and remove legacy UNIX peer support.
> Various fixes and improvements for vsock

- Makefile
- README.md
- examples/Makefile
- init/init.c
This contains just miscellaneous improvements.
> Miscellaneous improvements

- src/devices/src/virtio/fs/macos/passthrough.rs
On macOS, listxattr was generating a buffer missing the NULL at the
end of each attribute.
> devices/fs: fix listxattr on macOS

- Cargo.lock
- src/cpuid/src/brand_string.rs
- src/devices/src/virtio/console/device.rs
- src/devices/src/virtio/fs/linux/passthrough.rs
- src/logger/src/logger.rs
* Remove trailing colon , make build happy.
* Remove deprecated `compare_and_swap`
* Bump package to current release.
> Remove AtomicUsize deprecations 

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
This release includes changes in TSI behavior, so bump minor to
v1.1.0.
> Bump version to v1.1.0

- init/init.c
Don't rely on the cmdline_secret size returned by fstat() to determine
the length of the secret. Also, unlink the cmdline_secret file once it
has been read, and overwrite "pass" with zeroes ones used.
> sev: don't rely on cmdline_secret size and unlink

- src/devices/src/virtio/fs/macos/passthrough.rs
When a file is unlinked while still opened, the server might lose
access to it if it's expunged from LruCache, as we no longer have a
cached path to re-open it.
To prevent this from happening, we add the map "pinned_files" where we
keep track of unlinked but still referenced inodes. Once the inode is
no longer referenced, the entry is removed from "pinned_files" and, as
consequence, the associated "File" is dropped and the file descriptor
closed.
Signed-off-by: Sergio Lopez <slp@sinrega.org>
> fs/macos: keep track of unlinked files

- examples/Makefile
> examples/Makefile: Remove launch-tee binary on make clean

- Cargo.lock
- Makefile
- src/arch/src/x86_64/mod.rs
- src/arch/src/x86_64/regs.rs
- src/cpuid/src/transformer/intel.rs
- src/devices/src/legacy/serial.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/console/device.rs
- src/devices/src/virtio/fs/descriptor_utils.rs
- src/devices/src/virtio/fs/fuse.rs
- src/devices/src/virtio/fs/linux/passthrough.rs
- src/devices/src/virtio/fs/server.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/muxer.rs
- src/devices/src/virtio/vsock/muxer_thread.rs
- src/devices/src/virtio/vsock/tcp.rs
- src/devices/src/virtio/vsock/udp.rs
- src/hvf/src/lib.rs
- src/kernel/src/cmdline/mod.rs
- src/libkrun/Cargo.toml
- src/utils/src/time.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/linux/tee/amdsev.rs
- src/vmm/src/linux/tee/amdsnp.rs
- src/vmm/src/linux/vstate.rs
- src/vmm/src/signal_handler.rs
This release includes initial SNP support and a fix when parsing environment variables in init.c, bump release number to v1.4.9.
> Bump version to v1.4.9

- src/arch/src/lib.rs
- src/cpuid/src/common.rs
- src/devices/src/legacy/i8042.rs
- src/devices/src/virtio/fs/descriptor_utils.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/muxer.rs
- src/devices/src/virtio/vsock/proxy.rs
- src/hvf/src/lib.rs
- src/libkrun/src/lib.rs
- src/polly/src/event_manager.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/kvm/mmio.rs
- src/vmm/src/device_manager/legacy.rs
- src/vmm/src/lib.rs
- src/vmm/src/linux/vstate.rs
- src/vmm/src/vmm_config/fs.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vmm_config/vsock.rs
After an update in our CI, clippy has started complaining about new things. Let's address them.
> Fix CI clippy

- src/devices/src/virtio/vsock/reaper.rs
This fixes #112 ...
This fixes recv_timeout so that it blocks:
1. until the next event arrives (Duration.MAX)
2. until next socket can be closed (<5s)
Please don't ask me to explain the exact relation between this fix and the socket leak in #112 :)  - I do not have enough understanding for KVM Host-Guest networking works. All I know is that this fixes a valid bug in reaper and after that I can no longer reproduce #112.
In regards to testing I  have this patch with the scenario in #112 for ~6 days.
And you can clearly see that the `TCP_inuse` no longer grows proportionally with `TCP_alloc` metric:
> VSOCK: fix reaper timeout

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
Bump minor number, we're now at version to v1.5.1
> Bump version to v1.5.1

- src/devices/src/virtio/fs/linux/passthrough.rs
Userspace may request to read beyond the end of the file, in which case we should return as many bytes as possible (which can be zero).
Fixes: #136
> devices/fs: fix reading the end of init.krun

- include/libkrun.h
- src/libkrun/src/lib.rs
- src/vmm/src/builder.rs
- src/vmm/src/resources.rs
Extend the API to allow configuring multiple independent virtio-fs with different tags and paths.
> lib: allow having multiple virtio-fs devices

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
To API breaking changes this time, just bump release.
> Bump version to 1.9.1

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
This is a minor release temporarily bundling imago.
> Bump version 1.10.1

- README.md
> fix krunkit typo in README

- examples/launch-tee.c
- src/vmm/src/linux/tee/amdsev.rs
Drop bare SEV in favor of SEV-ES, and apply some other minor fixes.
> Drop bare SEV in favor of SEV-ES

- Cargo.lock
- src/devices/Cargo.toml
> upgrade imago to 0.1.4

- Cargo.lock
- Makefile
This is quite a large release with new API additions which clearly deserves a full minor bump.
> Bump version to 1.11.0

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
This is a minor release with fixes that are small but convenient for packaging.
> Bump version to 1.11.1

- init/init.c
I was playing with different VM configurations and was able to run a system from a raw disk image instead of virtiofs.
It basically works, I just need a custom cmdline and an actual copy of init.krun on the image filesystem.
The only issue is that init assumes root is always virtiofs and uses the KRUN_EXIT_CODE_IOCTL which will fail.
To avoid the error on conventional filesystems, we can first call statfs and check `f_type`.
> init.c: only use KRUN_EXIT_CODE_IOCTL if root is really virtiofs

- Cargo.lock
- Makefile
- src/libkrun/Cargo.toml
Set up the stage for a new release.
> Bump version to 1.15.0
